### ISSUE TITLE
USER STORY: As a Developer, I can store my code remotely for version control and collaboration with my teammates.

### ISSUE THREAD

**Issue by VCGithubCode** [VCGithubCode/the-love-bugs#31]
EPIC: <epic>

As a **Developer** I can **store my code remotely** so that **I will can do version control and collaboration with my teammates.**

**Acceptance Criteria**
- [x] Repository created on Github

- [x] Availability for users on either Gitpod or VSCode to be able to clone the project, work on it locally, and push their changes to the main repo for review and possible adaptation into main code

- [x] Ability for developers to be able to fork, create branches, create pull requests, and see the project kanban board

**Tasks**

- [x] Create Repo

- [x] Make initial commit with necessary dependencies

- [x]  Inform teammates of repo location

- [x] Create Project and categories

- [x] Start creating Epic template

**Comment by VCGithubCode** [comment]
Done
