### ISSUE TITLE
USER STORY: As a developer, I can reference meeting notes and other important moments in the hackathon team channel

### ISSUE THREAD

**Issue by VCGithubCode** [VCGithubCode/the-love-bugs#34]
EPIC: Meeting Minutes

As a **Developer** I can **reference meeting notes** so that **I have up to date information I need to proceed in the project**

**Acceptance Criteria**

- [x] Team has been informed where to find huddle meeting minutes and knows how to access it
- [x] Ability for team members to search the document and find images, links, and other important points to help keep the needle moving if someone isn’t available to answer questions
- [x] Ability for all team members to see progress in the project and to be encouraged by the amount of creativity and effort already committed into the project by all members during brainstorming and team alignment sessions
- [x] Developers are provided with a high level of transparency in the project planning and can see right in the slack channel all task statuses (other members progress and additional resources such as API information, idea proposals and so on)

**Tasks**

- [] Task 1:  Keep a record of notes in meetings of important moments that will concern progress of development 
- [x] Task 2: Summarize notes into most important or relevant information for this stage of the project
- [x] Task 3:  Provide continuous access to notes to all members of the team 
- [x] Task 4: Lock notes and create version history to prevent information loss or accidental changes 
- [x] Task 5:  Save frequently to provide an adequate version control method in case overall plans change
- [x] Task 6: Reflect on results presented by team members and create plan to make next sprint and next meeting more successful
