### ISSUE TITLE
USER STORY: As a developer, I can build on different parts of the application and see the effects on other parts other parts of the app

### ISSUE THREAD

**Issue by VCGithubCode** [VCGithubCode/the-love-bugs#44]
EPIC: Create model

As a **Developer** I can **see progress in the frontend and backend** so that **the development process approaches mvp more efficiently.**

**Acceptance Criteria**
-[x] Initial models should provide a solid structure that facilitates smooth communication and interaction between different parts of the application

**Tasks**

- [x]  Task 1:  Create initial models
- [x]  Task 2:  Test in deployment environment
- [x]  Task 3:  Push to repo
