### ISSUE TITLE
USER STORY: As a Visitor I can understand in less than 7 seconds what the app is for and less than 30 seconds how and where to sign up

### ISSUE THREAD

**Issue by VCGithubCode** [VCGithubCode/the-love-bugs#45]
EPIC: Landing page

As a **visitor to the app** I can **see a clearly defined purpose on the visually appealing landing page and a brief introduction of the apps features** so that **I can decide quickly if I am curious enough to explore the app further**

**Acceptance Criteria**
- [] The landing page has a clear header with the app name and logo.
- [x] Navigation links to the About page, Contact page, Login, and Sign Up are easily accessible.
- [] The main section introduces the app and highlights its key features with an introduction for the user.
- [] Design and layout are visually appealing and align with the app's entire theme.

**Tasks**
- [] Design the header with the app logo and or app name and navigation links (Sign up and Login.)
- [] Create an attractive main section with a form to sign in
- [] Implement a responsive design for various devices.
